language: php
php:
  - 7.4
  - 8.0
  - 8.1

services:
  - docker

before_script:
  - docker version
  - composer install --no-scripts

script:
  - docker run --rm -v $(pwd):/grumphp madlenka/grumphp-docker grumphp run
