language: php
php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer install --no-scripts --no-suggest

script:
  - vendor/bin/grumphp run
